GET http://localhost:8081/authors

###
GET http://localhost:8081/books

###
GET http://localhost:8081/author/50

###
POST http://localhost:8081/authors
Content-Type: application/json

< ../../src/main/resources/authorlist.json
###
POST http://localhost:8081/author
Content-Type: application/json
{
    "name": "damn",
    "books": [44],
    "favorites": 4
}
###
DELETE http://localhost:8081/author/54
###

POST http://localhost:8081/author
Content-Type: application/json

{
    "name": "damn",
    "books": [
      {
        "title": "Alice",
        "cover": "\"E:\\Videos\\Anime\\waaa\\1602997426091.jpg\"",
        "genres": [
          "Romance",
          "Fantasy"
        ],
        "language": "Português",
        "pages": 254,
        "globalscore": 8.0
      }
    ],
    "favorites": 4
  }
